### ISSUE TITLE
Check links on Environmental Scan

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#82]
Make sure links are still working and if they're going to paywaylls

**Comment by GentrySteven** [comment]
I've gone through and made issues for the ones that appear to be broken/problematic/otherwise not useful. I'll do one more pass of the page before our next meeting, though, just to make sure I got everything.

@kateefly, the "Citations" issue (#90) has a ton of changes associated with it. 

I kept the problematic links in one issue due to the time that I did this, but I would be happy to assign each problematic link its own issue if you want!

**Comment by kateefly** [comment]
Thanks @GentrySteven ! I'll add a discussion of problematic links to the next agenda and we can assign the issues then.

**Comment by GentrySteven** [comment]
Closed via #101
